/*
Com o try, você pode tentar executar algo, caso der errado vai para o catch, que deve
mostrar uma mensagem de erro, indicando onde é o erro

É MUITO ÚTIL PARA DEBUGGER
*/

try{
    let a = 2 + b
}catch(falarOErro){
    console.log(falarOErro)
}

console.log('teste')

/*
Note que aqui, NÃO PARA O CÓDIGO
*/